# Generated by Django 5.0.1 on 2024-01-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CacheData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("most_expensive_cache_minutes", models.IntegerField()),
                ("vendor_data_cache_minutes", models.IntegerField()),
                ("most_expensive_last_update", models.DateTimeField()),
                ("vendor_data_last_update", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="MeliItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("permalink", models.URLField()),
            ],
        ),
    ]
