# Generated by Django 5.0.1 on 2024-01-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CacheData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("most_expensive_last_update", models.DateTimeField()),
                ("vendor_data_last_update", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="MeliItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("permalink", models.URLField()),
            ],
            options={
                "ordering": ["-price"],
            },
        ),
        migrations.CreateModel(
            name="MeliVendor",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("total_items", models.IntegerField(default=0)),
                ("average_price", models.FloatField(default=0.0)),
                ("gold_special", models.IntegerField(default=0)),
                ("gold_pro", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-total_items"],
            },
        ),
    ]
