# Generated by Django 5.0.1 on 2024-01-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_create_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="meliitem",
            name="thumbnail",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
