# Generated by Django 5.0.1 on 2024-01-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_set_up_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeliVendor",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("total_items", models.IntegerField(default=0)),
                ("average_price", models.FloatField(default=0.0)),
                ("gold_special", models.IntegerField(default=0)),
                ("gold_pro", models.IntegerField(default=0)),
            ],
        ),
    ]
